### ISSUE TITLE
请求怎么开发这种完整的插件？

### ISSUE THREAD

**Issue by leosxie** [ShowJoy/vscode-element-helper#1]
是否有空写一篇文章啊，或者能否联系请教

**Comment by ShowJoy** [comment]
写过关于atom插件的开发，思路差不多，你可以参考下[如何开发一个 Atom 插件](https://zhuanlan.zhihu.com/p/27913291)

**Comment by leosxie** [comment]
收到感谢🙏

发自我的 iPhone
